repos:
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black", "."]
        types: [python]
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 26.1a1
    hooks:
      - id: black
        name: black
        args: ["."]
        types: [python]
        pass_filenames: false

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8
        args: ["--ignore=E203,E221,E501,W503", "--exclude=.venv", "."]
        types: [python]
        pass_filenames: false
