services:
  crawler:
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - open-ahrefs

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - open-ahrefs

  redis_ui:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redis_ui_data:/data
    depends_on:
      - redis
    networks:
      - open-ahrefs

volumes:
  redis_data:
  redis_ui_data:

networks:
  open-ahrefs:
    external: true
